# TCL File Generated by Component Editor 15.1
# Wed Sep 07 16:46:06 MSK 2016
# DO NOT MODIFY


# 
# i2cMaster "I2C Master" v1.0
#  2016.09.07.16:46:06
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module i2cMaster
# 
set_module_property DESCRIPTION ""
set_module_property NAME i2cMaster
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "I2C Master"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL i2cMasterHw
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file i2cMasterHw.sv SYSTEM_VERILOG PATH ../../rtl/i2cMasterHw.sv TOP_LEVEL_FILE
add_fileset_file i2cMaster.sv SYSTEM_VERILOG PATH ../../rtl/i2cMaster.sv
add_fileset_file i2cAvalon.sv SYSTEM_VERILOG PATH ../../rtl/i2cAvs.sv
add_fileset_file i2cControl.sv SYSTEM_VERILOG PATH ../../rtl/i2cControl.sv
add_fileset_file i2cLine.sv SYSTEM_VERILOG PATH ../../rtl/i2cLine.sv
add_fileset_file i2cTick.sv SYSTEM_VERILOG PATH ../../rtl/i2cTick.sv


# 
# parameters
# 
add_parameter CLK_MASTER_FRQ INTEGER 50000000 ""
set_parameter_property CLK_MASTER_FRQ DEFAULT_VALUE 50000000
set_parameter_property CLK_MASTER_FRQ DISPLAY_NAME CLK_MASTER_FRQ
set_parameter_property CLK_MASTER_FRQ WIDTH ""
set_parameter_property CLK_MASTER_FRQ TYPE INTEGER
set_parameter_property CLK_MASTER_FRQ UNITS Hertz
set_parameter_property CLK_MASTER_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CLK_MASTER_FRQ DESCRIPTION ""
set_parameter_property CLK_MASTER_FRQ HDL_PARAMETER true
add_parameter SCLK_I2C_FRQ INTEGER 500000 ""
set_parameter_property SCLK_I2C_FRQ DEFAULT_VALUE 500000
set_parameter_property SCLK_I2C_FRQ DISPLAY_NAME SCLK_I2C_FRQ
set_parameter_property SCLK_I2C_FRQ WIDTH ""
set_parameter_property SCLK_I2C_FRQ TYPE INTEGER
set_parameter_property SCLK_I2C_FRQ UNITS Hertz
set_parameter_property SCLK_I2C_FRQ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SCLK_I2C_FRQ DESCRIPTION ""
set_parameter_property SCLK_I2C_FRQ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset reset
set_interface_property avs bitsPerSymbol 8
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 0
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 1
set_interface_property avs readWaitStates 0
set_interface_property avs readWaitTime 0
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input 2
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 8
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_readdata readdata Output 8
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avs
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset 0
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq ins_irq irq Output 1


# 
# connection point i2cLine
# 
add_interface i2cLine conduit end
set_interface_property i2cLine associatedClock clk
set_interface_property i2cLine associatedReset reset
set_interface_property i2cLine ENABLED true
set_interface_property i2cLine EXPORT_OF ""
set_interface_property i2cLine PORT_NAME_MAP ""
set_interface_property i2cLine CMSIS_SVD_VARIABLES ""
set_interface_property i2cLine SVD_ADDRESS_GROUP ""

add_interface_port i2cLine coe_sdat sdat Bidir 1
add_interface_port i2cLine coe_sclk sclk Bidir 1

